In [1]:
%load_ext autoreload
%autoreload 2
import hw4
import numpy as np

In [25]:
# x = np.array([2,3,4])
x = [2,3,4]
y = np.array([1,2,3])
z = x - y
#print(np.linalg.norm(x), np.linalg.norm(y), np.linalg.norm(z), np.linalg.norm(x - y))
#print(len(x))
#print(len(np.array(x)))
type(x)

list

In [28]:
x = [np.array([1,2,3]), np.array([4,5,6]), np.array([7,8,9])]
print(type(x))
np.mean(x)

<class 'list'>


5.0

In [10]:
x = np.array([np.array([1,2,3]), np.array([4,5,6]), np.array([7,8,9])])
print(x)
#x[1,1]
np.count_nonzero(x == 1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


1

In [2]:
data = hw4.load_data("countries.csv")
country_names = [row["Country"] for row in data]
features = [hw4.calc_features(row) for row in data]
features_normalized = hw4.normalize_features(features)

n = 10
Z_raw = hw4.hac(features[-n:])
#Z_normalized = hac(features_normalized[:n])

hw4.fig_hac(Z_raw, country_names[-n:])

KeyError: 10